// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action XBMControlAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.Notebook notebook2;
    
    private Gtk.VBox vbox3;
    
    private Gtk.ComboBox cbShareType;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TreeView tvShareBrowser;
    
    private Gtk.Label label2;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.Label label1;
    
    private Gtk.Fixed fixed1;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.XBMControlAction = new Gtk.Action("XBMControlAction", Mono.Unix.Catalog.GetString("XBMControl"), null, null);
        this.XBMControlAction.ShortLabel = Mono.Unix.Catalog.GetString("XBMControl");
        w1.Add(this.XBMControlAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-quit");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("XBMControl Evo");
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='XBMControlAction' action='XBMControlAction'><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 300;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.notebook2 = new Gtk.Notebook();
        this.notebook2.WidthRequest = 300;
        this.notebook2.CanFocus = true;
        this.notebook2.Name = "notebook2";
        this.notebook2.CurrentPage = 0;
        // Container child notebook2.Gtk.Notebook+NotebookChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.cbShareType = Gtk.ComboBox.NewText();
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("music"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("video"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("pictures"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("files"));
        this.cbShareType.Name = "cbShareType";
        this.cbShareType.Active = 0;
        this.vbox3.Add(this.cbShareType);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.cbShareType]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.tvShareBrowser = new Gtk.TreeView();
        this.tvShareBrowser.CanFocus = true;
        this.tvShareBrowser.Name = "tvShareBrowser";
        this.GtkScrolledWindow.Add(this.tvShareBrowser);
        this.vbox3.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
        w5.Position = 1;
        this.notebook2.Add(this.vbox3);
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Shares");
        this.notebook2.SetTabLabel(this.vbox3, this.label2);
        this.label2.ShowAll();
        this.hpaned1.Add(this.notebook2);
        Gtk.Paned.PanedChild w7 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.notebook2]));
        w7.Resize = false;
        w7.Shrink = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 0;
        // Notebook tab
        Gtk.Label w8 = new Gtk.Label();
        w8.Visible = true;
        this.notebook1.Add(w8);
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("page1");
        this.notebook1.SetTabLabel(w8, this.label1);
        this.label1.ShowAll();
        this.hpaned1.Add(this.notebook1);
        this.vbox1.Add(this.hpaned1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
        w10.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.fixed1 = new Gtk.Fixed();
        this.fixed1.HeightRequest = 80;
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        this.vbox1.Add(this.fixed1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
        w11.Position = 2;
        w11.Expand = false;
        w11.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox1.Add(this.statusbar1);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
        w12.Position = 3;
        w12.Expand = false;
        w12.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 852;
        this.DefaultHeight = 636;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.QuitAction.Activated += new System.EventHandler(this.OnExit);
        this.cbShareType.Changed += new System.EventHandler(this.PopulateShareBrowser);
        this.tvShareBrowser.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.ExpandDirectory);
    }
}
