// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action XBMControlAction;
    
    private Gtk.Action QuitAction;
    
    private Gtk.Action XBMCAction;
    
    private Gtk.Action PlaylistAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action UpdateMusicLibraryAction;
    
    private Gtk.Action UpdateVideoLibraryAction;
    
    private Gtk.Action UpdateLibraryAction;
    
    private Gtk.Action MusicAction;
    
    private Gtk.Action VideoAction;
    
    private Gtk.Action RestartAction;
    
    private Gtk.Action RebootAction;
    
    private Gtk.Action ShutdownAction;
    
    private Gtk.Action ConfigurationAction;
    
    private Gtk.Action aClearPlaylist;
    
    private Gtk.Action openAction;
    
    private Gtk.Action saveAction;
    
    private Gtk.Action saveAsAction;
    
    private Gtk.Action refreshPlaylist;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.Notebook nbBrowser;
    
    private Gtk.VBox vbox3;
    
    private Gtk.ComboBox cbShareType;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TreeView tvShareBrowser;
    
    private Gtk.Label label2;
    
    private Gtk.Notebook nbDataContainer;
    
    private Gtk.Label label1;
    
    private Gtk.VBox vbox2;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TreeView tvPlaylist;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.Label label3;
    
    private Gtk.Label label4;
    
    private Gtk.Fixed fixed1;
    
    private Gtk.HScale hsVolume;
    
    private Gtk.HScale hsProgress;
    
    private Gtk.ToggleButton tbMute;
    
    private Gtk.Button bPrevious;
    
    private Gtk.ToggleButton tbPlay;
    
    private Gtk.ToggleButton tbStop;
    
    private Gtk.Button bNext;
    
    private Gtk.Button bRepeat;
    
    private Gtk.Button bShuffle;
    
    private Gtk.Button bPartyMode;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.XBMControlAction = new Gtk.Action("XBMControlAction", Mono.Unix.Catalog.GetString("XBMControl"), null, null);
        this.XBMControlAction.ShortLabel = Mono.Unix.Catalog.GetString("XBMControl");
        w1.Add(this.XBMControlAction, null);
        this.QuitAction = new Gtk.Action("QuitAction", Mono.Unix.Catalog.GetString("_Quit"), null, "gtk-disconnect");
        this.QuitAction.ShortLabel = Mono.Unix.Catalog.GetString("_Quit");
        w1.Add(this.QuitAction, null);
        this.XBMCAction = new Gtk.Action("XBMCAction", Mono.Unix.Catalog.GetString("XBMC"), null, null);
        this.XBMCAction.ShortLabel = Mono.Unix.Catalog.GetString("XBMC");
        w1.Add(this.XBMCAction, null);
        this.PlaylistAction = new Gtk.Action("PlaylistAction", Mono.Unix.Catalog.GetString("Playlist"), null, null);
        this.PlaylistAction.ShortLabel = Mono.Unix.Catalog.GetString("Playlist");
        w1.Add(this.PlaylistAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.UpdateMusicLibraryAction = new Gtk.Action("UpdateMusicLibraryAction", Mono.Unix.Catalog.GetString("Update music library"), null, null);
        this.UpdateMusicLibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Update music library");
        w1.Add(this.UpdateMusicLibraryAction, null);
        this.UpdateVideoLibraryAction = new Gtk.Action("UpdateVideoLibraryAction", Mono.Unix.Catalog.GetString("Update video library"), null, null);
        this.UpdateVideoLibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Update video library");
        w1.Add(this.UpdateVideoLibraryAction, null);
        this.UpdateLibraryAction = new Gtk.Action("UpdateLibraryAction", Mono.Unix.Catalog.GetString("Update Library"), null, null);
        this.UpdateLibraryAction.ShortLabel = Mono.Unix.Catalog.GetString("Library");
        w1.Add(this.UpdateLibraryAction, null);
        this.MusicAction = new Gtk.Action("MusicAction", Mono.Unix.Catalog.GetString("Music"), null, "gtk-harddisk");
        this.MusicAction.ShortLabel = Mono.Unix.Catalog.GetString("Update music library");
        w1.Add(this.MusicAction, null);
        this.VideoAction = new Gtk.Action("VideoAction", Mono.Unix.Catalog.GetString("Video"), null, "gtk-harddisk");
        this.VideoAction.ShortLabel = Mono.Unix.Catalog.GetString("Update video library");
        w1.Add(this.VideoAction, null);
        this.RestartAction = new Gtk.Action("RestartAction", Mono.Unix.Catalog.GetString("Restart"), null, "gtk-refresh");
        this.RestartAction.ShortLabel = Mono.Unix.Catalog.GetString("Restart");
        w1.Add(this.RestartAction, null);
        this.RebootAction = new Gtk.Action("RebootAction", Mono.Unix.Catalog.GetString("Reboot"), null, "gtk-refresh");
        this.RebootAction.ShortLabel = Mono.Unix.Catalog.GetString("Reboot");
        w1.Add(this.RebootAction, null);
        this.ShutdownAction = new Gtk.Action("ShutdownAction", Mono.Unix.Catalog.GetString("Shutdown"), null, "gtk-quit");
        this.ShutdownAction.ShortLabel = Mono.Unix.Catalog.GetString("Shutdown");
        w1.Add(this.ShutdownAction, null);
        this.ConfigurationAction = new Gtk.Action("ConfigurationAction", Mono.Unix.Catalog.GetString("Configuration"), null, "gtk-edit");
        this.ConfigurationAction.ShortLabel = Mono.Unix.Catalog.GetString("_Preferences");
        w1.Add(this.ConfigurationAction, null);
        this.aClearPlaylist = new Gtk.Action("aClearPlaylist", null, null, "gtk-new");
        w1.Add(this.aClearPlaylist, null);
        this.openAction = new Gtk.Action("openAction", null, null, "gtk-open");
        w1.Add(this.openAction, null);
        this.saveAction = new Gtk.Action("saveAction", null, null, "gtk-save");
        w1.Add(this.saveAction, null);
        this.saveAsAction = new Gtk.Action("saveAsAction", null, null, "gtk-save-as");
        w1.Add(this.saveAsAction, null);
        this.refreshPlaylist = new Gtk.Action("refreshPlaylist", null, null, "gtk-refresh");
        w1.Add(this.refreshPlaylist, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("XBMControl Evo");
        this.WindowPosition = ((Gtk.WindowPosition)(1));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='XBMControlAction' action='XBMControlAction'><menuitem name='ConfigurationAction' action='ConfigurationAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='XBMCAction' action='XBMCAction'><menu name='UpdateLibraryAction' action='UpdateLibraryAction'><menuitem name='MusicAction' action='MusicAction'/><menuitem name='VideoAction' action='VideoAction'/></menu><menuitem name='RestartAction' action='RestartAction'/><menuitem name='RebootAction' action='RebootAction'/><menuitem name='ShutdownAction' action='ShutdownAction'/></menu><menu name='PlaylistAction' action='PlaylistAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 300;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.nbBrowser = new Gtk.Notebook();
        this.nbBrowser.WidthRequest = 300;
        this.nbBrowser.CanFocus = true;
        this.nbBrowser.Name = "nbBrowser";
        this.nbBrowser.CurrentPage = 0;
        // Container child nbBrowser.Gtk.Notebook+NotebookChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.cbShareType = Gtk.ComboBox.NewText();
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("music"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("video"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("pictures"));
        this.cbShareType.AppendText(Mono.Unix.Catalog.GetString("files"));
        this.cbShareType.Name = "cbShareType";
        this.cbShareType.Active = 0;
        this.vbox3.Add(this.cbShareType);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.cbShareType]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.tvShareBrowser = new Gtk.TreeView();
        this.tvShareBrowser.CanFocus = true;
        this.tvShareBrowser.Name = "tvShareBrowser";
        this.GtkScrolledWindow.Add(this.tvShareBrowser);
        this.vbox3.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
        w5.Position = 1;
        this.nbBrowser.Add(this.vbox3);
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Shares");
        this.nbBrowser.SetTabLabel(this.vbox3, this.label2);
        this.label2.ShowAll();
        this.hpaned1.Add(this.nbBrowser);
        Gtk.Paned.PanedChild w7 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.nbBrowser]));
        w7.Resize = false;
        w7.Shrink = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.nbDataContainer = new Gtk.Notebook();
        this.nbDataContainer.CanFocus = true;
        this.nbDataContainer.Name = "nbDataContainer";
        this.nbDataContainer.CurrentPage = 1;
        // Notebook tab
        Gtk.Label w8 = new Gtk.Label();
        w8.Visible = true;
        this.nbDataContainer.Add(w8);
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Info");
        this.nbDataContainer.SetTabLabel(w8, this.label1);
        this.label1.ShowAll();
        // Container child nbDataContainer.Gtk.Notebook+NotebookChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.tvPlaylist = new Gtk.TreeView();
        this.tvPlaylist.CanFocus = true;
        this.tvPlaylist.Name = "tvPlaylist";
        this.tvPlaylist.Reorderable = true;
        this.GtkScrolledWindow1.Add(this.tvPlaylist);
        this.vbox2.Add(this.GtkScrolledWindow1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
        w10.Position = 0;
        // Container child vbox2.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='aClearPlaylist' action='aClearPlaylist'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><toolitem name='refreshPlaylist' action='refreshPlaylist'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.toolbar1.IconSize = ((Gtk.IconSize)(3));
        this.vbox2.Add(this.toolbar1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
        w11.Position = 1;
        w11.Expand = false;
        w11.Fill = false;
        this.nbDataContainer.Add(this.vbox2);
        Gtk.Notebook.NotebookChild w12 = ((Gtk.Notebook.NotebookChild)(this.nbDataContainer[this.vbox2]));
        w12.Position = 1;
        // Notebook tab
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Playlist");
        this.nbDataContainer.SetTabLabel(this.vbox2, this.label3);
        this.label3.ShowAll();
        // Notebook tab
        Gtk.Label w13 = new Gtk.Label();
        w13.Visible = true;
        this.nbDataContainer.Add(w13);
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Configuration");
        this.nbDataContainer.SetTabLabel(w13, this.label4);
        this.label4.ShowAll();
        this.hpaned1.Add(this.nbDataContainer);
        this.vbox1.Add(this.hpaned1);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
        w15.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.fixed1 = new Gtk.Fixed();
        this.fixed1.HeightRequest = 55;
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.hsVolume = new Gtk.HScale(null);
        this.hsVolume.TooltipMarkup = "Volume";
        this.hsVolume.WidthRequest = 120;
        this.hsVolume.CanFocus = true;
        this.hsVolume.Name = "hsVolume";
        this.hsVolume.Adjustment.Upper = 100;
        this.hsVolume.Adjustment.PageIncrement = 10;
        this.hsVolume.Adjustment.StepIncrement = 1;
        this.hsVolume.Adjustment.Value = 51.8987341772152;
        this.hsVolume.DrawValue = false;
        this.hsVolume.Digits = 0;
        this.hsVolume.ValuePos = ((Gtk.PositionType)(2));
        this.fixed1.Add(this.hsVolume);
        Gtk.Fixed.FixedChild w16 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.hsVolume]));
        w16.X = 730;
        w16.Y = 7;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.hsProgress = new Gtk.HScale(null);
        this.hsProgress.TooltipMarkup = "Progress";
        this.hsProgress.WidthRequest = 420;
        this.hsProgress.CanFocus = true;
        this.hsProgress.Name = "hsProgress";
        this.hsProgress.Adjustment.Upper = 100;
        this.hsProgress.Adjustment.PageIncrement = 10;
        this.hsProgress.Adjustment.StepIncrement = 1;
        this.hsProgress.DrawValue = false;
        this.hsProgress.Digits = 0;
        this.hsProgress.ValuePos = ((Gtk.PositionType)(2));
        this.fixed1.Add(this.hsProgress);
        Gtk.Fixed.FixedChild w17 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.hsProgress]));
        w17.X = 300;
        w17.Y = 7;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.tbMute = new Gtk.ToggleButton();
        this.tbMute.TooltipMarkup = "Toggle Mute";
        this.tbMute.WidthRequest = 32;
        this.tbMute.HeightRequest = 32;
        this.tbMute.CanFocus = true;
        this.tbMute.Name = "tbMute";
        this.tbMute.UseUnderline = true;
        // Container child tbMute.Gtk.Container+ContainerChild
        Gtk.Alignment w18 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w19 = new Gtk.HBox();
        w19.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w20 = new Gtk.Image();
        w20.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_volume-mute", Gtk.IconSize.Button, 20);
        w19.Add(w20);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w22 = new Gtk.Label();
        w19.Add(w22);
        w18.Add(w19);
        this.tbMute.Add(w18);
        this.fixed1.Add(this.tbMute);
        Gtk.Fixed.FixedChild w26 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.tbMute]));
        w26.X = 850;
        w26.Y = 5;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.bPrevious = new Gtk.Button();
        this.bPrevious.TooltipMarkup = "Previous";
        this.bPrevious.WidthRequest = 35;
        this.bPrevious.HeightRequest = 35;
        this.bPrevious.CanFocus = true;
        this.bPrevious.Name = "bPrevious";
        this.bPrevious.UseUnderline = true;
        // Container child bPrevious.Gtk.Container+ContainerChild
        Gtk.Alignment w27 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w28 = new Gtk.HBox();
        w28.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w29 = new Gtk.Image();
        w29.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-media-previous", Gtk.IconSize.LargeToolbar, 24);
        w28.Add(w29);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w31 = new Gtk.Label();
        w28.Add(w31);
        w27.Add(w28);
        this.bPrevious.Add(w27);
        this.fixed1.Add(this.bPrevious);
        Gtk.Fixed.FixedChild w35 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.bPrevious]));
        w35.X = 14;
        w35.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.tbPlay = new Gtk.ToggleButton();
        this.tbPlay.TooltipMarkup = "Play";
        this.tbPlay.WidthRequest = 35;
        this.tbPlay.HeightRequest = 35;
        this.tbPlay.CanFocus = true;
        this.tbPlay.Name = "tbPlay";
        this.tbPlay.UseUnderline = true;
        // Container child tbPlay.Gtk.Container+ContainerChild
        Gtk.Alignment w36 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w37 = new Gtk.HBox();
        w37.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w38 = new Gtk.Image();
        w38.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-media-play", Gtk.IconSize.LargeToolbar, 24);
        w37.Add(w38);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w40 = new Gtk.Label();
        w37.Add(w40);
        w36.Add(w37);
        this.tbPlay.Add(w36);
        this.fixed1.Add(this.tbPlay);
        Gtk.Fixed.FixedChild w44 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.tbPlay]));
        w44.X = 46;
        w44.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.tbStop = new Gtk.ToggleButton();
        this.tbStop.TooltipMarkup = "Stop";
        this.tbStop.WidthRequest = 35;
        this.tbStop.HeightRequest = 35;
        this.tbStop.CanFocus = true;
        this.tbStop.Name = "tbStop";
        this.tbStop.UseUnderline = true;
        // Container child tbStop.Gtk.Container+ContainerChild
        Gtk.Alignment w45 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w46 = new Gtk.HBox();
        w46.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w47 = new Gtk.Image();
        w47.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-media-stop", Gtk.IconSize.LargeToolbar, 24);
        w46.Add(w47);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w49 = new Gtk.Label();
        w46.Add(w49);
        w45.Add(w46);
        this.tbStop.Add(w45);
        this.fixed1.Add(this.tbStop);
        Gtk.Fixed.FixedChild w53 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.tbStop]));
        w53.X = 78;
        w53.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.bNext = new Gtk.Button();
        this.bNext.TooltipMarkup = "Next";
        this.bNext.WidthRequest = 35;
        this.bNext.HeightRequest = 35;
        this.bNext.CanFocus = true;
        this.bNext.Name = "bNext";
        this.bNext.UseUnderline = true;
        // Container child bNext.Gtk.Container+ContainerChild
        Gtk.Alignment w54 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w55 = new Gtk.HBox();
        w55.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w56 = new Gtk.Image();
        w56.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-media-next", Gtk.IconSize.LargeToolbar, 24);
        w55.Add(w56);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w58 = new Gtk.Label();
        w55.Add(w58);
        w54.Add(w55);
        this.bNext.Add(w54);
        this.fixed1.Add(this.bNext);
        Gtk.Fixed.FixedChild w62 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.bNext]));
        w62.X = 110;
        w62.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.bRepeat = new Gtk.Button();
        this.bRepeat.TooltipMarkup = "Toggle Repeat Modes";
        this.bRepeat.WidthRequest = 28;
        this.bRepeat.HeightRequest = 28;
        this.bRepeat.CanFocus = true;
        this.bRepeat.Name = "bRepeat";
        this.bRepeat.UseUnderline = true;
        // Container child bRepeat.Gtk.Container+ContainerChild
        Gtk.Alignment w63 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w64 = new Gtk.HBox();
        w64.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w65 = new Gtk.Image();
        w65.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-redo", Gtk.IconSize.Menu, 16);
        w64.Add(w65);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w67 = new Gtk.Label();
        w64.Add(w67);
        w63.Add(w64);
        this.bRepeat.Add(w63);
        this.fixed1.Add(this.bRepeat);
        Gtk.Fixed.FixedChild w71 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.bRepeat]));
        w71.X = 155;
        w71.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.bShuffle = new Gtk.Button();
        this.bShuffle.TooltipMarkup = "Toggle Shuffel Mode";
        this.bShuffle.WidthRequest = 28;
        this.bShuffle.HeightRequest = 28;
        this.bShuffle.CanFocus = true;
        this.bShuffle.Name = "bShuffle";
        this.bShuffle.UseUnderline = true;
        // Container child bShuffle.Gtk.Container+ContainerChild
        Gtk.Alignment w72 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w73 = new Gtk.HBox();
        w73.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w74 = new Gtk.Image();
        w74.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_chart-toggle-legend", Gtk.IconSize.Menu, 16);
        w73.Add(w74);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w76 = new Gtk.Label();
        w73.Add(w76);
        w72.Add(w73);
        this.bShuffle.Add(w72);
        this.fixed1.Add(this.bShuffle);
        Gtk.Fixed.FixedChild w80 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.bShuffle]));
        w80.X = 180;
        w80.Y = 4;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.bPartyMode = new Gtk.Button();
        this.bPartyMode.TooltipMarkup = "Toggle Party Mode";
        this.bPartyMode.WidthRequest = 28;
        this.bPartyMode.HeightRequest = 28;
        this.bPartyMode.CanFocus = true;
        this.bPartyMode.Name = "bPartyMode";
        this.bPartyMode.UseUnderline = true;
        // Container child bPartyMode.Gtk.Container+ContainerChild
        Gtk.Alignment w81 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w82 = new Gtk.HBox();
        w82.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w83 = new Gtk.Image();
        w83.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_filters", Gtk.IconSize.Menu, 16);
        w82.Add(w83);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w85 = new Gtk.Label();
        w82.Add(w85);
        w81.Add(w82);
        this.bPartyMode.Add(w81);
        this.fixed1.Add(this.bPartyMode);
        Gtk.Fixed.FixedChild w89 = ((Gtk.Fixed.FixedChild)(this.fixed1[this.bPartyMode]));
        w89.X = 205;
        w89.Y = 4;
        this.vbox1.Add(this.fixed1);
        Gtk.Box.BoxChild w90 = ((Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
        w90.Position = 2;
        w90.Expand = false;
        w90.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 898;
        this.DefaultHeight = 636;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.QuitAction.Activated += new System.EventHandler(this.OnExit);
        this.MusicAction.Activated += new System.EventHandler(this.click_UpdateMusicLibrary);
        this.VideoAction.Activated += new System.EventHandler(this.click_UpdateVideoLibrary);
        this.aClearPlaylist.Activated += new System.EventHandler(this.aClearPlaylist_click);
        this.refreshPlaylist.Activated += new System.EventHandler(this.click_RefreshPlaylist);
        this.cbShareType.Changed += new System.EventHandler(this.change_cbShareBrowser);
        this.tvShareBrowser.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.tvShareBrowser_release);
        this.tvPlaylist.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.tvPlaylist_buttonRelease);
        this.hsVolume.ValueChanged += new System.EventHandler(this.hsVolume_valueChanged);
        this.hsProgress.ChangeValue += new Gtk.ChangeValueHandler(this.hsProgress_changeValue);
        this.tbMute.Released += new System.EventHandler(this.tbMute_released);
        this.bPrevious.Released += new System.EventHandler(this.bPrevious_released);
        this.tbPlay.Released += new System.EventHandler(this.tbPlay_released);
        this.tbStop.Released += new System.EventHandler(this.tbStop_released);
        this.bNext.Released += new System.EventHandler(this.bNext_released);
        this.bRepeat.Activated += new System.EventHandler(this.bRepeat_click);
        this.bShuffle.Activated += new System.EventHandler(this.bShuffle_click);
        this.bPartyMode.Activated += new System.EventHandler(this.bPartyMode_click);
    }
}
